spring.application.name=bookstore
springdoc.swagger-ui.path=/swagger
server.port=5000
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# GCP Configuration
gcp.project-id=springbootbookstore
gcp.bucket-name=bookstore-content
gcp.credentials.location=C:/Users/nawst/IdeaProjects/SpringBootBookStore/SpringBootBookStore/api/springbootbookstore-f853687c84c0.json
#gcp.credentials.location=file:"../../../springbootbookstore-f853687c84c0.json"
